fix: prevent publishing with wrong package version

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -25,9 +25,30 @@ jobs:
     name: Lint & type-check
     uses: ./.github/workflows/lint-test.yml
 
+  packagejson:
+    name: Check package.json versions
+    runs-on: ubuntu-latest
+    if: github.ref_type == 'tag'
+    steps:
+      - name: Check out the repo
+        uses: actions/checkout@v4
+
+      - name: Check package.json versions against tag
+        run: |
+          errors=0
+          for file in package.json packages/*/package.json
+          do
+            if cat $file | jq .version | grep -Fqvx '"${{ github.ref_name }}"'
+            then
+              echo "::error file=$file::The version here does not match the Git tag you pushed (${{ github.ref_name }}). This would cause no NPM packages to be published."
+              errors=1
+            fi
+          done
+          exit $errors
+
   docker:
     name: Push Docker image to GitHub Packages
-    needs: lint
+    needs: [lint, packagejson]
     runs-on: ubuntu-latest
     permissions:
       packages: write
@@ -106,7 +127,7 @@ jobs:
   # This is disabled on forks since you probably don't need to upload your own packages
   npm:
     name: Publish JS packages
-    needs: lint
+    needs: [lint, packagejson]
     permissions:
       packages: write
       contents: read
